import { Component } from "@angular/core";
import { IonicPage, NavController, NavParams } from "ionic-angular";

/**
 * Generated class for the RegisterPage page.
 *
 * See http://ionicframework.com/docs/components/#navigation for more info
 * on Ionic pages and navigation.
 */

@IonicPage()
@Component({
  selector: "page-register",
  templateUrl: "register.html"
})
export class RegisterPage {
  public states: any[];
  public districts: any[];

  public selectedDistricts: any[];

  public sState: any;
  public sDistrict: any;

  constructor(public navCtrl: NavController, public navParams: NavParams) {
    this.initializeState();
    this.initializeDistrict();
  }

  ionViewDidLoad() {
    console.log("ionViewDidLoad RegisterPage");
  }

  initializeState() {
    this.states = [
      { id: 1, name: "Andaman & Nicobar" },
      { id: 2, name: "Andhra Pradesh" },
      { id: 3, name: "Arunachal Pradesh" },
      { id: 4, name: "Assam" },
      { id: 4, name: "Bihar" }

    ];
  }

  initializeDistrict() {
    this.districts = [
      //Andaman & Nicobar

      { name: " Alipur ", state_id: 1 },
      { name: " Andaman Island ", state_id: 1 },
      { name: " Anderson Island ", state_id: 1 },
      { name: " Arainj-Laka-Punga ", state_id: 1 },
      { name: " Austinabad ", state_id: 1 },
      { name: " Bamboo Flat ", state_id: 1 },
      { name: " Barren Island ", state_id: 1 },
      { name: " Beadonabad ", state_id: 1 },
      { name: " Betapur ", state_id: 1 },
      { name: " Bindraban ", state_id: 1 },
      { name: " Bonington ", state_id: 1 },
      { name: " Brookesabad ", state_id: 1 },
      { name: " Cadell Point ", state_id: 1 },
      { name: " Calicut ", state_id: 1 },
      { name: " Chetamale ", state_id: 1 },
      { name: " Cinque Islands ", state_id: 1 },
      { name: " Defence Island ", state_id: 1 },
      { name: " Digilpur ", state_id: 1 },
      { name: " Dolyganj ", state_id: 1 },
      { name: " Flat Island ", state_id: 1 },
      { name: " Geinyale ", state_id: 1 },
      { name: " Great Coco Island ", state_id: 1 },
      { name: " Haddo ", state_id: 1 },
      { name: " Havelock Island ", state_id: 1 },
      { name: " Henry Lawrence Island ", state_id: 1 },
      { name: " Herbertabad ", state_id: 1 },
      { name: " Hobdaypur ", state_id: 1 },
      { name: " Ilichar ", state_id: 1 },
      { name: " Ingoie ", state_id: 1 },
      { name: " Inteview Island ", state_id: 1 },
      { name: " Jangli Ghat ", state_id: 1 },
      { name: " Jhon Lawrence Island ", state_id: 1 },
      { name: " Karen ", state_id: 1 },
      { name: " Kartara ", state_id: 1 },
      { name: " KYD Islannd ", state_id: 1 },
      { name: " Landfall Island ", state_id: 1 },
      { name: " Little Andmand ", state_id: 1 },
      { name: " Little Coco Island ", state_id: 1 },
      { name: " Long Island ", state_id: 1 },
      { name: " Maimyo ", state_id: 1 },
      { name: " Malappuram ", state_id: 1 },
      { name: " Manglutan ", state_id: 1 },
      { name: " Manpur ", state_id: 1 },
      { name: " Mitha Khari ", state_id: 1 },
      { name: " Neill Island ", state_id: 1 },
      { name: " Nicobar Island ", state_id: 1 },
      { name: " North Brother Island ", state_id: 1 },
      { name: " North Passage Island ", state_id: 1 },
      { name: " North Sentinel Island ", state_id: 1 },
      { name: " Nothen Reef Island ", state_id: 1 },
      { name: " Outram Island ", state_id: 1 },
      { name: " Pahlagaon ", state_id: 1 },
      { name: " Palalankwe ", state_id: 1 },
      { name: " Passage Island ", state_id: 1 },
      { name: " Phaiapong ", state_id: 1 },
      { name: " Phoenix Island ", state_id: 1 },
      { name: " Port Blair ", state_id: 1 },
      { name: " Preparis Island ", state_id: 1 },
      { name: " Protheroepur ", state_id: 1 },
      { name: " Rangachang ", state_id: 1 },
      { name: " Rongat ", state_id: 1 },
      { name: " Rutland Island ", state_id: 1 },
      { name: " Sabari ", state_id: 1 },
      { name: " Saddle Peak ", state_id: 1 },
      { name: " Shadipur ", state_id: 1 },
      { name: " Smith Island ", state_id: 1 },
      { name: " Sound Island ", state_id: 1 },
      { name: " South Sentinel Island ", state_id: 1 },
      { name: " Spike Island ", state_id: 1 },
      { name: " Tarmugli Island ", state_id: 1 },
      { name: " Taylerabad ", state_id: 1 },
      { name: " Titaije ", state_id: 1 },
      { name: " Toibalawe ", state_id: 1 },
      { name: " Tusonabad ", state_id: 1 },
      { name: " West Island ", state_id: 1 },
      { name: " Wimberleyganj ", state_id: 1 },
      { name: " Yadita ", state_id: 1 },

      //Andhra Pradesh

      { name: " Achampet ", state_id: 2 },
      { name: " Adilabad ", state_id: 2 },
      { name: " Adoni ", state_id: 2 },
      { name: " Alampur ", state_id: 2 },
      { name: " Allagadda ", state_id: 2 },
      { name: " Alur ", state_id: 2 },
      { name: " Amalapuram ", state_id: 2 },
      { name: " Amangallu ", state_id: 2 },
      { name: " Anakapalle ", state_id: 2 },
      { name: " Anantapur ", state_id: 2 },
      { name: " Andole ", state_id: 2 },
      { name: " Araku ", state_id: 2 },
      { name: " Armoor ", state_id: 2 },
      { name: " Asifabad ", state_id: 2 },
      { name: " Aswaraopet ", state_id: 2 },
      { name: " Atmakur ", state_id: 2 },
      { name: " B. Kothakota ", state_id: 2 },
      { name: " Badvel ", state_id: 2 },
      { name: " Banaganapalle ", state_id: 2 },
      { name: " Bandar ", state_id: 2 },
      { name: " Bangarupalem ", state_id: 2 },
      { name: " Banswada ", state_id: 2 },
      { name: " Bapatla ", state_id: 2 },
      { name: " Bellampalli ", state_id: 2 },
      { name: " Bhadrachalam ", state_id: 2 },
      { name: " Bhainsa ", state_id: 2 },
      { name: " Bheemunipatnam ", state_id: 2 },
      { name: " Bhimadole ", state_id: 2 },
      { name: " Bhimavaram ", state_id: 2 },
      { name: " Bhongir ", state_id: 2 },
      { name: " Bhooragamphad ", state_id: 2 },
      { name: " Boath ", state_id: 2 },
      { name: " Bobbili ", state_id: 2 },
      { name: " Bodhan ", state_id: 2 },
      { name: " Chandoor ", state_id: 2 },
      { name: " Chavitidibbalu ", state_id: 2 },
      { name: " Chejerla ", state_id: 2 },
      { name: " Chepurupalli ", state_id: 2 },
      { name: " Cherial ", state_id: 2 },
      { name: " Chevella ", state_id: 2 },
      { name: " Chinnor ", state_id: 2 },
      { name: " Chintalapudi ", state_id: 2 },
      { name: " Chintapalle ", state_id: 2 },
      { name: " Chirala ", state_id: 2 },
      { name: " Chittoor ", state_id: 2 },
      { name: " Chodavaram ", state_id: 2 },
      { name: " Cuddapah ", state_id: 2 },
      { name: " Cumbum ", state_id: 2 },
      { name: " Darsi ", state_id: 2 },
      { name: " Devarakonda ", state_id: 2 },
      { name: " Dharmavaram ", state_id: 2 },
      { name: " Dichpalli ", state_id: 2 },
      { name: " Divi ", state_id: 2 },
      { name: " Donakonda ", state_id: 2 },
      { name: " Dronachalam ", state_id: 2 },
      { name: " East Godavari ", state_id: 2 },
      { name: " Eluru ", state_id: 2 },
      { name: " Eturnagaram ", state_id: 2 },
      { name: " Gadwal ", state_id: 2 },
      { name: " Gajapathinagaram ", state_id: 2 },
      { name: " Gajwel ", state_id: 2 },
      { name: " Garladinne ", state_id: 2 },
      { name: " Giddalur ", state_id: 2 },
      { name: " Godavari ", state_id: 2 },
      { name: " Gooty ", state_id: 2 },
      { name: " Gudivada ", state_id: 2 },
      { name: " Gudur ", state_id: 2 },
      { name: " Guntur ", state_id: 2 },
      { name: " Hindupur ", state_id: 2 },
      { name: " Hunsabad ", state_id: 2 },
      { name: " Huzurabad ", state_id: 2 },
      { name: " Huzurnagar ", state_id: 2 },
      { name: " Hyderabad ", state_id: 2 },
      { name: " Ibrahimpatnam ", state_id: 2 },
      { name: " Jaggayyapet ", state_id: 2 },
      { name: " Jagtial ", state_id: 2 },
      { name: " Jammalamadugu ", state_id: 2 },
      { name: " Jangaon ", state_id: 2 },
      { name: " Jangareddygudem ", state_id: 2 },
      { name: " Jannaram ", state_id: 2 },
      { name: " Kadiri ", state_id: 2 },
      { name: " Kaikaluru ", state_id: 2 },
      { name: " Kakinada ", state_id: 2 },
      { name: " Kalwakurthy ", state_id: 2 },
      { name: " Kalyandurg ", state_id: 2 },
      { name: " Kamalapuram ", state_id: 2 },
      { name: " Kamareddy ", state_id: 2 },
      { name: " Kambadur ", state_id: 2 },
      { name: " Kanaganapalle ", state_id: 2 },
      { name: " Kandukuru ", state_id: 2 },
      { name: " Kanigiri ", state_id: 2 },
      { name: " Karimnagar ", state_id: 2 },
      { name: " Kavali ", state_id: 2 },
      { name: " Khammam ", state_id: 2 },
      { name: " Khanapur (AP) ", state_id: 2 },
      { name: " Kodangal ", state_id: 2 },
      { name: " Koduru ", state_id: 2 },
      { name: " Koilkuntla ", state_id: 2 },
      { name: " Kollapur ", state_id: 2 },
      { name: " Kothagudem ", state_id: 2 },
      { name: " Kovvur ", state_id: 2 },
      { name: " Krishna ", state_id: 2 },
      { name: " Krosuru ", state_id: 2 },
      { name: " Kuppam ", state_id: 2 },
      { name: " Kurnool ", state_id: 2 },
      { name: " Lakkireddipalli ", state_id: 2 },
      { name: " Madakasira ", state_id: 2 },
      { name: " Madanapalli ", state_id: 2 },
      { name: " Madhira ", state_id: 2 },
      { name: " Madnur ", state_id: 2 },
      { name: " Mahabubabad ", state_id: 2 },
      { name: " Mahabubnagar ", state_id: 2 },
      { name: " Mahadevapur ", state_id: 2 },
      { name: " Makthal ", state_id: 2 },
      { name: " Mancherial ", state_id: 2 },
      { name: " Mandapeta ", state_id: 2 },
      { name: " Mangalagiri ", state_id: 2 },
      { name: " Manthani ", state_id: 2 },
      { name: " Markapur ", state_id: 2 },
      { name: " Marturu ", state_id: 2 },
      { name: " Medachal ", state_id: 2 },
      { name: " Medak ", state_id: 2 },
      { name: " Medarmetla ", state_id: 2 },
      { name: " Metpalli ", state_id: 2 },
      { name: " Mriyalguda ", state_id: 2 },
      { name: " Mulug ", state_id: 2 },
      { name: " Mylavaram ", state_id: 2 },
      { name: " Nagarkurnool ", state_id: 2 },
      { name: " Nalgonda ", state_id: 2 },
      { name: " Nallacheruvu ", state_id: 2 },
      { name: " Nampalle ", state_id: 2 },
      { name: " Nandigama ", state_id: 2 },
      { name: " Nandikotkur ", state_id: 2 },
      { name: " Nandyal ", state_id: 2 },
      { name: " Narasampet ", state_id: 2 },
      { name: " Narasaraopet ", state_id: 2 },
      { name: " Narayanakhed ", state_id: 2 },
      { name: " Narayanpet ", state_id: 2 },
      { name: " Narsapur ", state_id: 2 },
      { name: " Narsipatnam ", state_id: 2 },
      { name: " Nazvidu ", state_id: 2 },
      { name: " Nelloe ", state_id: 2 },
      { name: " Nellore ", state_id: 2 },
      { name: " Nidamanur ", state_id: 2 },
      { name: " Nirmal ", state_id: 2 },
      { name: " Nizamabad ", state_id: 2 },
      { name: " Nuguru ", state_id: 2 },
      { name: " Ongole ", state_id: 2 },
      { name: " Outsarangapalle ", state_id: 2 },
      { name: " Paderu ", state_id: 2 },
      { name: " Pakala ", state_id: 2 },
      { name: " Palakonda ", state_id: 2 },
      { name: " Paland ", state_id: 2 },
      { name: " Palmaneru ", state_id: 2 },
      { name: " Pamuru ", state_id: 2 },
      { name: " Pargi ", state_id: 2 },
      { name: " Parkal ", state_id: 2 },
      { name: " Parvathipuram ", state_id: 2 },
      { name: " Pathapatnam ", state_id: 2 },
      { name: " Pattikonda ", state_id: 2 },
      { name: " Peapalle ", state_id: 2 },
      { name: " Peddapalli ", state_id: 2 },
      { name: " Peddapuram ", state_id: 2 },
      { name: " Penukonda ", state_id: 2 },
      { name: " Piduguralla ", state_id: 2 },
      { name: " Piler ", state_id: 2 },
      { name: " Pithapuram ", state_id: 2 },
      { name: " Podili ", state_id: 2 },
      { name: " Polavaram ", state_id: 2 },
      { name: " Prakasam ", state_id: 2 },
      { name: " Proddatur ", state_id: 2 },
      { name: " Pulivendla ", state_id: 2 },
      { name: " Punganur ", state_id: 2 },
      { name: " Putturu ", state_id: 2 },
      { name: " Rajahmundri ", state_id: 2 },
      { name: " Rajampeta ", state_id: 2 },
      { name: " Ramachandrapuram ", state_id: 2 },
      { name: " Ramannapet ", state_id: 2 },
      { name: " Rampachodavaram ", state_id: 2 },
      { name: " Rangareddy ", state_id: 2 },
      { name: " Rapur ", state_id: 2 },
      { name: " Rayachoti ", state_id: 2 },
      { name: " Rayadurg ", state_id: 2 },
      { name: " Razole ", state_id: 2 },
      { name: " Repalle ", state_id: 2 },
      { name: " Saluru ", state_id: 2 },
      { name: " Sangareddy ", state_id: 2 },
      { name: " Sathupalli ", state_id: 2 },
      { name: " Sattenapalle ", state_id: 2 },
      { name: " Satyavedu ", state_id: 2 },
      { name: " Shadnagar ", state_id: 2 },
      { name: " Siddavattam ", state_id: 2 },
      { name: " Siddipet ", state_id: 2 },
      { name: " Sileru ", state_id: 2 },
      { name: " Sircilla ", state_id: 2 },
      { name: " Sirpur Kagaznagar ", state_id: 2 },
      { name: " Sodam ", state_id: 2 },
      { name: " Sompeta ", state_id: 2 },
      { name: " Srikakulam ", state_id: 2 },
      { name: " Srikalahasthi ", state_id: 2 },
      { name: " Srisailam ", state_id: 2 },
      { name: " Srungavarapukota ", state_id: 2 },
      { name: " Sudhimalla ", state_id: 2 },
      { name: " Sullarpet ", state_id: 2 },
      { name: " Tadepalligudem ", state_id: 2 },
      { name: " Tadipatri ", state_id: 2 },
      { name: " Tanduru ", state_id: 2 },
      { name: " Tanuku ", state_id: 2 },
      { name: " Tekkali ", state_id: 2 },
      { name: " Tenali ", state_id: 2 },
      { name: " Thungaturthy ", state_id: 2 },
      { name: " Tirivuru ", state_id: 2 },
      { name: " Tirupathi ", state_id: 2 },
      { name: " Tuni ", state_id: 2 },
      { name: " Udaygiri ", state_id: 2 },
      { name: " Ulvapadu ", state_id: 2 },
      { name: " Uravakonda ", state_id: 2 },
      { name: " Utnor ", state_id: 2 },
      { name: " V.R. Puram ", state_id: 2 },
      { name: " Vaimpalli ", state_id: 2 },
      { name: " Vayalpad ", state_id: 2 },
      { name: " Venkatgiri ", state_id: 2 },
      { name: " Venkatgirikota ", state_id: 2 },
      { name: " Vijayawada ", state_id: 2 },
      { name: " Vikrabad ", state_id: 2 },
      { name: " Vinjamuru ", state_id: 2 },
      { name: " Vinukonda ", state_id: 2 },
      { name: " Visakhapatnam ", state_id: 2 },
      { name: " Vizayanagaram ", state_id: 2 },
      { name: " Vizianagaram ", state_id: 2 },
      { name: " Vuyyuru ", state_id: 2 },
      { name: " Wanaparthy ", state_id: 2 },
      { name: " Warangal ", state_id: 2 },
      { name: " Wardhannapet ", state_id: 2 },
      { name: " Yelamanchili ", state_id: 2 },
      { name: " Yelavaram ", state_id: 2 },
      { name: " Yeleswaram ", state_id: 2 },
      { name: " Yellandu ", state_id: 2 },
      { name: " Yellanuru ", state_id: 2 },
      { name: " Yellareddy ", state_id: 2 },
      { name: " Yerragondapalem ", state_id: 2 },
      { name: " Zahirabad ", state_id: 2 },

      //Arunachal Pradesh

      { name: " Along ", state_id: 3 },
      { name: " Anini ", state_id: 3 },
      { name: " Anjaw ", state_id: 3 },
      { name: " Bameng ", state_id: 3 },
      { name: " Basar ", state_id: 3 },
      { name: " Changlang ", state_id: 3 },
      { name: " Chowkhem ", state_id: 3 },
      { name: " Daporizo ", state_id: 3 },
      { name: " Dibang Valley ", state_id: 3 },
      { name: " Dirang ", state_id: 3 },
      { name: " Hayuliang ", state_id: 3 },
      { name: " Huri ", state_id: 3 },
      { name: " Itanagar ", state_id: 3 },
      { name: " Jairampur ", state_id: 3 },
      { name: " Kalaktung ", state_id: 3 },
      { name: " Kameng ", state_id: 3 },
      { name: " Khonsa ", state_id: 3 },
      { name: " Kolaring ", state_id: 3 },
      { name: " Kurung Kumey ", state_id: 3 },
      { name: " Lohit ", state_id: 3 },
      { name: " Lower Dibang Valley ", state_id: 3 },
      { name: " Lower Subansiri ", state_id: 3 },
      { name: " Mariyang ", state_id: 3 },
      { name: " Mechuka ", state_id: 3 },
      { name: " Miao ", state_id: 3 },
      { name: " Nefra ", state_id: 3 },
      { name: " Pakkekesang ", state_id: 3 },
      { name: " Pangin ", state_id: 3 },
      { name: " Papum Pare ", state_id: 3 },
      { name: " Passighat ", state_id: 3 },
      { name: " Roing ", state_id: 3 },
      { name: " Sagalee ", state_id: 3 },
      { name: " Seppa ", state_id: 3 },
      { name: " Siang ", state_id: 3 },
      { name: " Tali ", state_id: 3 },
      { name: " Taliha ", state_id: 3 },
      { name: " Tawang ", state_id: 3 },
      { name: " Tezu ", state_id: 3 },
      { name: " Tirap ", state_id: 3 },
      { name: " Tuting ", state_id: 3 },
      { name: " Upper Siang ", state_id: 3 },
      { name: " Upper Subansiri ", state_id: 3 },
      { name: " Yiang Kiag ", state_id: 3 },
      { name: "", state_id: 3 },

      //Assam

      { name: " Abhayapuri ", state_id: 4 },
      { name: " Baithalangshu ", state_id: 4 },
      { name: " Barama ", state_id: 4 },
      { name: " Barpeta Road ", state_id: 4 },
      { name: " Bihupuria ", state_id: 4 },
      { name: " Bijni ", state_id: 4 },
      { name: " Bilasipara ", state_id: 4 },
      { name: " Bokajan ", state_id: 4 },
      { name: " Bokakhat ", state_id: 4 },
      { name: " Boko ", state_id: 4 },
      { name: " Bongaigaon ", state_id: 4 },
      { name: " Cachar ", state_id: 4 },
      { name: " Cachar Hills ", state_id: 4 },
      { name: " Darrang ", state_id: 4 },
      { name: " Dhakuakhana ", state_id: 4 },
      { name: " Dhemaji ", state_id: 4 },
      { name: " Dhubri ", state_id: 4 },
      { name: " Dibrugarh ", state_id: 4 },
      { name: " Digboi ", state_id: 4 },
      { name: " Diphu ", state_id: 4 },
      { name: " Goalpara ", state_id: 4 },
      { name: " Gohpur ", state_id: 4 },
      { name: " Golaghat ", state_id: 4 },
      { name: " Guwahati ", state_id: 4 },
      { name: " Hailakandi ", state_id: 4 },
      { name: " Hajo ", state_id: 4 },
      { name: " Halflong ", state_id: 4 },
      { name: " Hojai ", state_id: 4 },
      { name: " Howraghat ", state_id: 4 },
      { name: " Jorhat ", state_id: 4 },
      { name: " Kamrup ", state_id: 4 },
      { name: " Karbi Anglong ", state_id: 4 },
      { name: " Karimganj ", state_id: 4 },
      { name: " Kokarajhar ", state_id: 4 },
      { name: " Kokrajhar ", state_id: 4 },
      { name: " Lakhimpur ", state_id: 4 },
      { name: " Maibong ", state_id: 4 },
      { name: " Majuli ", state_id: 4 },
      { name: " Mangaldoi ", state_id: 4 },
      { name: " Mariani ", state_id: 4 },
      { name: " Marigaon ", state_id: 4 },
      { name: " Moranhat ", state_id: 4 },
      { name: " Morigaon ", state_id: 4 },
      { name: " Nagaon ", state_id: 4 },
      { name: " Nalbari ", state_id: 4 },
      { name: " Rangapara ", state_id: 4 },
      { name: " Sadiya ", state_id: 4 },
      { name: " Sibsagar ", state_id: 4 },
      { name: " Silchar ", state_id: 4 },
      { name: " Sivasagar ", state_id: 4 },
      { name: " Sonitpur ", state_id: 4 },
      { name: " Tarabarihat ", state_id: 4 },
      { name: " Tezpur ", state_id: 4 },
      { name: " Tinsukia ", state_id: 4 },
      { name: " Udalgiri ", state_id: 4 },
      { name: " Udalguri ", state_id: 4 },
      { name: " UdarbondhBarpeta ", state_id: 4 },

      //Bihar

      { name: " Adhaura ", state_id: 5 },
      { name: " Amarpur ", state_id: 5 },
      { name: " Araria ", state_id: 5 },
      { name: " Areraj ", state_id: 5 },
      { name: " Arrah ", state_id: 5 },
      { name: " Arwal ", state_id: 5 },
      { name: " Aurangabad ", state_id: 5 },
      { name: " Bagaha ", state_id: 5 },
      { name: " Banka ", state_id: 5 },
      { name: " Banmankhi ", state_id: 5 },
      { name: " Barachakia ", state_id: 5 },
      { name: " Barauni ", state_id: 5 },
      { name: " Barh ", state_id: 5 },
      { name: " Barosi ", state_id: 5 },
      { name: " Begusarai ", state_id: 5 },
      { name: " Benipatti ", state_id: 5 },
      { name: " Benipur ", state_id: 5 },
      { name: " Bettiah ", state_id: 5 },
      { name: " Bhabhua ", state_id: 5 },
      { name: " Bhagalpur ", state_id: 5 },
      { name: " Bhojpur ", state_id: 5 },
      { name: " Bidupur ", state_id: 5 },
      { name: " Biharsharif ", state_id: 5 },
      { name: " Bikram ", state_id: 5 },
      { name: " Bikramganj ", state_id: 5 },
      { name: " Birpur ", state_id: 5 },
      { name: " Buxar ", state_id: 5 },
      { name: " Chakai ", state_id: 5 },
      { name: " Champaran ", state_id: 5 },
      { name: " Chapara ", state_id: 5 },
      { name: " Dalsinghsarai ", state_id: 5 },
      { name: " Danapur ", state_id: 5 },
      { name: " Darbhanga ", state_id: 5 },
      { name: " Daudnagar ", state_id: 5 },
      { name: " Dhaka ", state_id: 5 },
      { name: " Dhamdaha ", state_id: 5 },
      { name: " Dumraon ", state_id: 5 },
      { name: " Ekma ", state_id: 5 },
      { name: " Forbesganj ", state_id: 5 },
      { name: " Gaya ", state_id: 5 },
      { name: " Gogri ", state_id: 5 },
      { name: " Gopalganj ", state_id: 5 },
      { name: " H.Kharagpur ", state_id: 5 },
      { name: " Hajipur ", state_id: 5 },
      { name: " Hathua ", state_id: 5 },
      { name: " Hilsa ", state_id: 5 },
      { name: " Imamganj ", state_id: 5 },
      { name: " Jahanabad ", state_id: 5 },
      { name: " Jainagar ", state_id: 5 },
      { name: " Jamshedpur ", state_id: 5 },
      { name: " Jamui ", state_id: 5 },
      { name: " Jehanabad ", state_id: 5 },
      { name: " Jhajha ", state_id: 5 },
      { name: " Jhanjharpur ", state_id: 5 },
      { name: " Kahalgaon ", state_id: 5 },
      { name: " Kaimur (Bhabua) ", state_id: 5 },
      { name: " Katihar ", state_id: 5 },
      { name: " Katoria ", state_id: 5 },
      { name: " Khagaria ", state_id: 5 },
      { name: " Kishanganj ", state_id: 5 },
      { name: " Korha ", state_id: 5 },
      { name: " Lakhisarai ", state_id: 5 },
      { name: " Madhepura ", state_id: 5 },
      { name: " Madhubani ", state_id: 5 },
      { name: " Maharajganj ", state_id: 5 },
      { name: " Mahua ", state_id: 5 },
      { name: " Mairwa ", state_id: 5 },
      { name: " Mallehpur ", state_id: 5 },
      { name: " Masrakh ", state_id: 5 },
      { name: " Mohania ", state_id: 5 },
      { name: " Monghyr ", state_id: 5 },
      { name: " Motihari ", state_id: 5 },
      { name: " Motipur ", state_id: 5 },
      { name: " Munger ", state_id: 5 },
      { name: " Muzaffarpur ", state_id: 5 },
      { name: " Nabinagar ", state_id: 5 },
      { name: " Nalanda ", state_id: 5 },
      { name: " Narkatiaganj ", state_id: 5 },
      { name: " Naugachia ", state_id: 5 },
      { name: " Nawada ", state_id: 5 },
      { name: " Pakribarwan ", state_id: 5 },
      { name: " Pakridayal ", state_id: 5 },
      { name: " Patna ", state_id: 5 },
      { name: " Phulparas ", state_id: 5 },
      { name: " Piro ", state_id: 5 },
      { name: " Pupri ", state_id: 5 },
      { name: " Purena ", state_id: 5 },
      { name: " Purnia ", state_id: 5 },
      { name: " Rafiganj ", state_id: 5 },
      { name: " Rajauli ", state_id: 5 },
      { name: " Ramnagar ", state_id: 5 },
      { name: " Raniganj ", state_id: 5 },
      { name: " Raxaul ", state_id: 5 },
      { name: " Rohtas ", state_id: 5 },
      { name: " Rosera ", state_id: 5 },
      { name: " S.Bakhtiarpur ", state_id: 5 },
      { name: " Saharsa ", state_id: 5 },
      { name: " Samastipur ", state_id: 5 },
      { name: " Saran ", state_id: 5 },
      { name: " Sasaram ", state_id: 5 },
      { name: " Seikhpura ", state_id: 5 },
      { name: " Sheikhpura ", state_id: 5 },
      { name: " Sheohar ", state_id: 5 },
      { name: " Sherghati ", state_id: 5 },
      { name: " Sidhawalia ", state_id: 5 },
      { name: " Singhwara ", state_id: 5 },
      { name: " Sitamarhi ", state_id: 5 },
      { name: " Siwan ", state_id: 5 },
      { name: " Sonepur ", state_id: 5 },
      { name: " Supaul ", state_id: 5 },
      { name: " Thakurganj ", state_id: 5 },
      { name: " Triveniganj ", state_id: 5 },
      { name: " Udakishanganj ", state_id: 5 },
      { name: " Vaishali ", state_id: 5 },
      { name: " Wazirganj ", state_id: 5 }
    ];
  }

  setDistrictValues(sState) {
    this.selectedDistricts = this.districts.filter(
      district => district.state_id == sState.id
    );
  }
}
